export default {
	// Login
	LOGIN_REQUEST: 'LOGIN_REQUEST',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAILED: 'LOGIN_FAILED',
	// Profile
	PROFILE_REQUEST: 'PROFILE_REQUEST',
	PROFILE_SUCCESS: 'PROFILE_SUCCESS',
	PROFILE_FAILED: 'PROFILE_FAILED',
	SELECTED_USER_PROFILE: 'SELECTED_USER_PROFILE',

	// Edit profile
	EDIT_PROFILE_OTP_REQUEST: 'EDIT_PROFILE_OTP_REQUEST',
	EDIT_PROFILE_OTP_SUCCESS: 'EDIT_PROFILE_OTP_SUCCESS',
	EDIT_PROFILE_OTP_FAILED: 'EDIT_PROFILE_OTP_FAILED',

	// Fetching
	FETCHING_START: 'FETCHING_START',
	FETCHING_STOP: 'FETCHING_STOP',
	FETCHING_FAILED: 'FETCHING_FAILED',

	// Verify OTP
	VERIFY_OTP_SUCCESS: 'VERIFY_OTP_SUCCESS',

	// Logout
	LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',

	// Getting Projects
	FETCH_PROJECT_REQUEST: 'FETCH_PROJECT_REQUEST',
	FETCH_PROJECT_SUCCESS: 'FETCH_PROJECT_SUCCESS',
	FETCH_PROJECT_FAILED: 'FETCH_PROJECT_FAILED',

	// SAVE
	SAVE_SUCCESSFULLY: 'SAVE_SUCCESSFULLY',
	SAVE_FAILED: 'SAVE_FAILED',

	// Project Checklists
	PROJECT_CHECKLISTS: 'PROJECT_CHECKLISTS',

	// Data Reset
	DATA_RESET: 'DATA_RESET',

	// Users
	GET_ALL_USERS: 'GET_ALL_USERS',

	// My Assigned Project
	MY_ASSIGNED_PROJECTS: 'MY_ASSIGNED_PROJECTS',

	FETCH_SUBMIT_REPORTS: 'FETCH_SUBMIT_REPORTS',
	SUBMITTED_ASSIGNED_PROJECT: 'SUBMITTED_ASSIGNED_PROJECT',
	MY_ASSIGNED_PROJECT: 'MY_ASSIGNED_PROJECT'

};
